"""add request_id for requestlog

Revision ID: e2b3556c3358
Revises: c330e656d79f
Create Date: 2026-07-04 00:48:41.798503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2b3556c3358'
down_revision: Union[str, Sequence[str], None] = 'c330e656d79f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "request_logs",
        sa.Column("request_id", sa.String(length=64), nullable=True)
    )

    op.execute("""
               UPDATE request_logs
               SET request_id = 'legacy-' || id
               WHERE request_id IS NULL
               """)

    op.alter_column(
        "request_logs",
        "request_id",
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_logs_request_id'), table_name='request_logs')
    op.drop_column('request_logs', 'request_id')
    # ### end Alembic commands ###
